### ISSUE TITLE
Import Documents: crashes if folder contains no readable files

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#620]
**Describe the bug**
Import Documents widget crashes when trying to load a folder with no readable files.

**To Reproduce**
Load a random folder without any .txt, .pdf or other files that the widget can read.

**Expected behavior**
No crash. None on output. Error: "Folder contains no readable files."

**Orange version:**
3.28.0.dev

**Text add-on version:**
1.3.1

**Additional context**
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owimportdocuments.py", line 547, in __onRunFinished
    self.corpus.name = "Documents"
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by ajdapretnar** [comment]
Additional issue when trying to cancel the above task:
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owimportdocuments.py", line 563, in cancel
    assert self.__pendingTask is not None
AssertionError
```

**Comment by ai-ellie** [comment]
I have same error just after I updated text add-on from 1.2.0 to 1.3.1.
